In [1]:
import numpy as np
import pandas as pd
points = np.random.rand(5,2)
names = ['A','B','C','D','E']
distances=np.empty((5,5))
for i in range(5):
    for j in range(5):
        distances[i][j] = np.linalg.norm(points[i]-points[j])
distDF = pd.DataFrame(distances, columns = names, index=names)
print(distDF)

          A         B         C         D         E
A  0.000000  0.492552  0.294016  0.269367  0.467866
B  0.492552  0.000000  0.734902  0.759404  0.291261
C  0.294016  0.734902  0.000000  0.164032  0.760104
D  0.269367  0.759404  0.164032  0.000000  0.720454
E  0.467866  0.291261  0.760104  0.720454  0.000000


In [3]:
print(distances)

[[0.         0.49255163 0.29401637 0.26936652 0.46786568]
 [0.49255163 0.         0.73490218 0.7594042  0.29126083]
 [0.29401637 0.73490218 0.         0.16403213 0.7601041 ]
 [0.26936652 0.7594042  0.16403213 0.         0.72045416]
 [0.46786568 0.29126083 0.7601041  0.72045416 0.        ]]
