In [6]:
import numpy as np

In [3]:
def jaccard_similarity(list1, list2):
    a = set(list1)
    b = set(list2)
    intersection = len(list(a.intersection(b)))
    union = (len(a) + len(b)) - intersection
    return float(intersection) / union

In [4]:
a = 'I am Sam.'
b = 'Sam I am.'
print(set(a).intersection(set(b)))
print((len(a) + len(b)) - len(set(a).intersection(set(b))))
jaccard_similarity(a,b)

{'m', 'S', 'a', '.', ' ', 'I'}
12


1.0

In [1]:
def correlation(x,y):
    fracA = sum((x-np.average(x))*(y-np.average(y)))
    fracB = np.sqrt(sum(np.power(x-np.average(x),2)))*np.sqrt(sum(np.power(y-np.average(y),2)))
    return fracA/fracB

def minkowski_distance(x,y,p):
    return np.sum(np.abs(x-y)**p)**(1/p)

def euclidianne_distance(x,y):
    return minkowski_distance(x,y,2)

def manhathan_distance(x,y):
    return minkowski_distance(x,y,1)

def lim_plus_distance(x,y):
    return np.max(np.abs(x-y))

def lim_min_distance(x,y):
    return np.min(np.abs(x-y))

def cosine(x,y):
    return np.sum(x*y)/(np.sqrt(np.sum(x**2))*np.sqrt(np.sum(y**2)))

In [11]:
X = np.random.rand(1,10)*100
Y = np.random.rand(1,10)*100

In [12]:
X,Y

(array([[16.35683878, 80.17193353, 16.52312599, 66.520801  , 10.01694846,
         25.24467412, 79.27988273, 16.11695601, 38.11557479, 68.97887391]]),
 array([[54.49909311, 61.68114843, 49.98269839, 66.09270842, 85.73994146,
         28.87163853, 66.25220512, 34.11457949, 70.34765014, 78.64092064]]))

In [13]:
print(correlation(X,Y))

[ 1.  1.  1.  1. -1.  1.  1.  1. -1.  1.]


In [14]:
print(minkowski_distance(X,Y,2))

101.43712412073315


In [15]:
print(euclidianne_distance(X,Y))

101.43712412073315


In [16]:
print(lim_min_distance(X,Y))

0.428092580241227


In [17]:
print(lim_plus_distance(X,Y))

75.72299299901896


In [18]:
print(cosine(X,Y))

0.8577473657849968


# END